Inventario/Inventario/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Inventario.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<InventarioModel> Inventario { get; set; }
    }
}

Inventario/Inventario/Models/ErrorViewModel.cs
using System;

namespace Inventario.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Inventario/Inventario/Models/InventarioModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Inventario.Models
{
    public class InventarioModel
    {
        [Key]
        public int Invid { get; set; }

        [Required(ErrorMessage = "Ingresa Nombre del objeto")]
        [Display(Name = "Nombre de Objeto")]
        public string Invname { get; set; }

        [Required(ErrorMessage = "Ingresa caracteristicas del objeto")]
        [Display(Name = "Caracteristicas")]
        public string Carac { get; set; }

        [Required(ErrorMessage = "Fije un Precio")]
        [Display(Name = "Precio")]
        public int Precio { get; set; }
    }
}

Inventario/Inventario/Controllers/InventarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Inventario.Models;
using Microsoft.AspNetCore.Mvc;

namespace Inventario.Controllers
{
    public class InventarioController : Controller
    {
        private readonly ApplicationDbContext _db;

        public InventarioController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var displaydata = _db.Inventario.ToList();
            return View(displaydata);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(InventarioModel nEmp)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nEmp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nEmp);
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getEmpDdetail = await _db.Inventario.FindAsync(id);
            return View(getEmpDdetail);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getEmpDdetail = await _db.Inventario.FindAsync(id);
            return View(getEmpDdetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(InventarioModel oldEmp)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldEmp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldEmp);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getEmpDdetail = await _db.Inventario.FindAsync(id);
            return View(getEmpDdetail);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getEmpDdetail = await _db.Inventario.FindAsync(id);
            _db.Inventario.Remove(getEmpDdetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Inventario/Inventario/Views/Inventario/Create.cshtml
@model Inventario.Models.InventarioModel

@{
    ViewData["Title"] = "Create";
}

<h1>Agregar Objeto</h1>

<h4>Objeto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Invname" class="control-label"></label>
                <input asp-for="Invname" class="form-control" />
                <span asp-validation-for="Invname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Carac" class="control-label"></label>
                <input asp-for="Carac" class="form-control" />
                <span asp-validation-for="Carac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voler al Inventario</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inventario/Inventario/Views/Inventario/Delete.cshtml
@model Inventario.Models.InventarioModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Objeto</h1>

<h3>¿Seguro quieres eliminar este objeto?</h3>
<div>
    <h4>Eliminar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a Inventario</a>
    </form>
</div>

Inventario/Inventario/Views/Inventario/Detail.cshtml
@model Inventario.Models.InventarioModel

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles</h1>

<div>
    <h4>Detalles de inventario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Invname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Invname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Invid }) |
    <a asp-action="Index">Volver al Inventario</a>
</div>

Inventario/Inventario/Views/Inventario/Edit.cshtml
@model Inventario.Models.InventarioModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Modificar Objeto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Invid" class="control-label"></label>
                <input asp-for="Invid" class="form-control" readonly/>
                <span asp-validation-for="Invid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Invname" class="control-label"></label>
                <input asp-for="Invname" class="form-control" />
                <span asp-validation-for="Invname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Carac" class="control-label"></label>
                <input asp-for="Carac" class="form-control" />
                <span asp-validation-for="Carac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver al Inventario</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inventario/Inventario/Views/Inventario/Index.cshtml
@model IEnumerable<Inventario.Models.InventarioModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Tabla de Objetos</h1>

<p>
    <a asp-action="Create">Agregar Objeto</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Invid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Invname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Carac)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Invid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Invname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Carac)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Invid }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Detalles", "Detail", new { id = item.Invid }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Invid }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

Inventario/Inventario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Inventario" asp-action="Index">Inventario</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventario" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Inventario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>